spring:
  profiles:
    active: "test"

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data.sql
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect