spring:
  profiles:
    active: "test"

logging:
  level:
    org.springframework.web: INFO
    com.example.newsapi: DEBUG
    org.hibernate: ERROR
  file:
    name: mylog.log

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:newsapi
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: /h2-console
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/newsapi
    username: postgres
    password: 6871
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
