// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package com.example.newsapi;

public interface CommentDTOOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommentDTO)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string date = 1;</code>
   */
  java.lang.String getDate();
  /**
   * <code>optional string date = 1;</code>
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>optional string text = 2;</code>
   */
  java.lang.String getText();
  /**
   * <code>optional string text = 2;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>optional string username = 3;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>optional string username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
