// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package com.example.newsapi;

/**
 * Protobuf type {@code Msg}
 */
public  final class Msg extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Msg)
    MsgOrBuilder {
  // Use Msg.newBuilder() to construct.
  private Msg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Msg() {
    foo_ = "";
    list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Msg(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            foo_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              list_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            list_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        list_ = list_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.newsapi.Dtos.internal_static_Msg_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.newsapi.Dtos.internal_static_Msg_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.newsapi.Msg.class, com.example.newsapi.Msg.Builder.class);
  }

  private int bitField0_;
  public static final int FOO_FIELD_NUMBER = 1;
  private volatile java.lang.Object foo_;
  /**
   * <code>optional string foo = 1;</code>
   */
  public java.lang.String getFoo() {
    java.lang.Object ref = foo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      foo_ = s;
      return s;
    }
  }
  /**
   * <code>optional string foo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFooBytes() {
    java.lang.Object ref = foo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      foo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LIST_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList list_;
  /**
   * <code>repeated string list = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getListList() {
    return list_;
  }
  /**
   * <code>repeated string list = 2;</code>
   */
  public int getListCount() {
    return list_.size();
  }
  /**
   * <code>repeated string list = 2;</code>
   */
  public java.lang.String getList(int index) {
    return list_.get(index);
  }
  /**
   * <code>repeated string list = 2;</code>
   */
  public com.google.protobuf.ByteString
      getListBytes(int index) {
    return list_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFooBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, foo_);
    }
    for (int i = 0; i < list_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, list_.getRaw(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFooBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, foo_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < list_.size(); i++) {
        dataSize += computeStringSizeNoTag(list_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getListList().size();
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.newsapi.Msg)) {
      return super.equals(obj);
    }
    com.example.newsapi.Msg other = (com.example.newsapi.Msg) obj;

    boolean result = true;
    result = result && getFoo()
        .equals(other.getFoo());
    result = result && getListList()
        .equals(other.getListList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + FOO_FIELD_NUMBER;
    hash = (53 * hash) + getFoo().hashCode();
    if (getListCount() > 0) {
      hash = (37 * hash) + LIST_FIELD_NUMBER;
      hash = (53 * hash) + getListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.newsapi.Msg parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.newsapi.Msg parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.newsapi.Msg parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.newsapi.Msg parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.newsapi.Msg parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.newsapi.Msg parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.newsapi.Msg parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.newsapi.Msg parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.newsapi.Msg parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.newsapi.Msg parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.newsapi.Msg prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Msg}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Msg)
      com.example.newsapi.MsgOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.newsapi.Dtos.internal_static_Msg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.newsapi.Dtos.internal_static_Msg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.newsapi.Msg.class, com.example.newsapi.Msg.Builder.class);
    }

    // Construct using com.example.newsapi.Msg.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      foo_ = "";

      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.newsapi.Dtos.internal_static_Msg_descriptor;
    }

    public com.example.newsapi.Msg getDefaultInstanceForType() {
      return com.example.newsapi.Msg.getDefaultInstance();
    }

    public com.example.newsapi.Msg build() {
      com.example.newsapi.Msg result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.example.newsapi.Msg buildPartial() {
      com.example.newsapi.Msg result = new com.example.newsapi.Msg(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.foo_ = foo_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        list_ = list_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.list_ = list_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.newsapi.Msg) {
        return mergeFrom((com.example.newsapi.Msg)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.newsapi.Msg other) {
      if (other == com.example.newsapi.Msg.getDefaultInstance()) return this;
      if (!other.getFoo().isEmpty()) {
        foo_ = other.foo_;
        onChanged();
      }
      if (!other.list_.isEmpty()) {
        if (list_.isEmpty()) {
          list_ = other.list_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureListIsMutable();
          list_.addAll(other.list_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.newsapi.Msg parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.newsapi.Msg) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object foo_ = "";
    /**
     * <code>optional string foo = 1;</code>
     */
    public java.lang.String getFoo() {
      java.lang.Object ref = foo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string foo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFooBytes() {
      java.lang.Object ref = foo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string foo = 1;</code>
     */
    public Builder setFoo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      foo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string foo = 1;</code>
     */
    public Builder clearFoo() {
      
      foo_ = getDefaultInstance().getFoo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string foo = 1;</code>
     */
    public Builder setFooBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      foo_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureListIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        list_ = new com.google.protobuf.LazyStringArrayList(list_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getListList() {
      return list_.getUnmodifiableView();
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public java.lang.String getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public com.google.protobuf.ByteString
        getListBytes(int index) {
      return list_.getByteString(index);
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public Builder setList(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
      list_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public Builder addList(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureListIsMutable();
      list_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public Builder addAllList(
        java.lang.Iterable<java.lang.String> values) {
      ensureListIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, list_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public Builder clearList() {
      list_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string list = 2;</code>
     */
    public Builder addListBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureListIsMutable();
      list_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Msg)
  }

  // @@protoc_insertion_point(class_scope:Msg)
  private static final com.example.newsapi.Msg DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.newsapi.Msg();
  }

  public static com.example.newsapi.Msg getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Msg>
      PARSER = new com.google.protobuf.AbstractParser<Msg>() {
    public Msg parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Msg(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Msg> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Msg> getParserForType() {
    return PARSER;
  }

  public com.example.newsapi.Msg getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

