// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dtos.proto

package com.example.newsapi;

public interface MsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Msg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string foo = 1;</code>
   */
  java.lang.String getFoo();
  /**
   * <code>optional string foo = 1;</code>
   */
  com.google.protobuf.ByteString
      getFooBytes();

  /**
   * <code>repeated string list = 2;</code>
   */
  java.util.List<java.lang.String>
      getListList();
  /**
   * <code>repeated string list = 2;</code>
   */
  int getListCount();
  /**
   * <code>repeated string list = 2;</code>
   */
  java.lang.String getList(int index);
  /**
   * <code>repeated string list = 2;</code>
   */
  com.google.protobuf.ByteString
      getListBytes(int index);
}
